### ISSUE TITLE
程序应该有个BUG

### ISSUE THREAD

**Issue by whiteany** [Vision-Intelligence-and-Robots-Group/SLSTT#2]
在trainer.py的132行，应当把model = torch.nn.DataParallel(model).cuda()缩进。不是放在if args.fintune下面。不然自己训练的时候用的不是GPU，而是CPU。

**Comment by whiteany** [comment]
还有个bug，在使用LOSO.py训练时，在trainer.py中有两个参数best_acc1 = 0和best_f1 = 0（在72行）。应当把这两参数放在def trainer里面。而且要放在global best_acc1和global best_f1下面赋值，不然会报错。如果不把这两个参数（best_acc1 = 0和best_f1 = 0）放在def  trainer里面，当有一个sub因为准确率达到100%退出训练时，接下来所有的sub都会因为best_acc1没有被赋值为0，而是接着上一个100%而退出训练。最终所有的sub都会只训练一次。

**Comment by yinlu0221** [comment]
你好，请问您跑成功了吗，能否分享一下vit的预训练文件B_16_imagenet1k.pth，我在网上找了很多不太匹配。
![Uploading image.png…]()

**Comment by yinlu0221** [comment]
能否分享一下vit的预训练文件呢，我在网上找了很多不匹配

**Comment by whiteany** [comment]
你好，这是我在网上找的一个预训练模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2)





 
你好，请问您跑成功了吗，能否分享一下vit的预训练文件B_16_imagenet1k.pth，我在网上找了很多不太匹配。
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

B_16_imagenet1k.pth (331.37M, 2023年12月01日 17:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2d6530334135728ee8dff77d13320a4a1d11545500540a0048010950561f5b5553061d07070b00485004095501025e0104075106352138273a54066c5c5f5902000b554704591615110d300e&code=ee03528e

**Comment by yinlu0221** [comment]
你好，谢谢你的分享，太感谢了。你跑成功了吗？能否加个微信或者QQ，有机会交流一下，向你请教一些问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2)





 你好，这是我在网上找的一个预训练模型。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月1日(星期三) 下午4:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2) 
 
 
 
 
 
   
 你好，请问您跑成功了吗，能否分享一下vit的预训练文件B_16_imagenet1k.pth，我在网上找了很多不太匹配。 
   
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
 
 
 从QQ邮箱发来的超大附件 
 
 B_16_imagenet1k.pth (331.37M, 2023年12月01日 17:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=2d6530334135728ee8dff77d13320a4a1d11545500540a0048010950561f5b5553061d07070b00485004095501025e0104075106352138273a54066c5c5f5902000b554704591615110d300e&amp;code=ee03528e

**Comment by yinlu0221** [comment]
这是我的微信18438869962，如果不方便的话，也没事儿的。这个代码有问题的话，我能否给您发邮件，希望能给我解答一些疑惑。谢谢您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2)





 你好，这是我在网上找的一个预训练模型。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月1日(星期三) 下午4:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2) 
 
 
 
 
 
   
 你好，请问您跑成功了吗，能否分享一下vit的预训练文件B_16_imagenet1k.pth，我在网上找了很多不太匹配。 
   
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
 
 
 从QQ邮箱发来的超大附件 
 
 B_16_imagenet1k.pth (331.37M, 2023年12月01日 17:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=2d6530334135728ee8dff77d13320a4a1d11545500540a0048010950561f5b5553061d07070b00485004095501025e0104075106352138273a54066c5c5f5902000b554704591615110d300e&amp;code=ee03528e

**Comment by whiteany** [comment]
你好，如有问题可以在此提问，如果我会的话可以为你解答。

**Comment by yinlu0221** [comment]
上面说把原始数据可以放在这个路径下面<preprocess/databases/casme2/data>，那是不是就是把casme2数据集图片放在这个路径。我看data_init.py文件只有读这个coding.csv的路径，没有见数据集路径。我运行LOSO.py文件，出现了这个错误“ValueError: num_samples should be a positive integer value, but got num_samples=0”，是不是数据集路径我没弄对。

**Comment by whiteany** [comment]
[README](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT#readme)里面有详细的解释，你需要放正确的数据集在正确的路径下面，然后运行[data_init.py](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/blob/main/preprocess/data_init.py)，就会得到处理好的光流图。建议先读一下论文，论文里有描述整个代码的原理以及数据处理过程有助于你理解代码。

**Comment by yinlu0221** [comment]
你好我把数据集放进了正确的路径，但是生成的LOF文件里面是空的。请问你在运行这个data_init.py过程中有没有遇见过这个问题

**Comment by whiteany** [comment]
要把之前出错生成的文件夹删除，再重新运行程序。不然有文件夹程序会认为已经运行完成。

**Comment by yinlu0221** [comment]
这个我知道，每一次运行前我就把错的LOF文件删掉，但是我发现是调用selectframes函数那一块出现了问题。onset_raw = cv2.imread(join(data_folder,'data','sub'+str(sample.Subject).zfill(2),sample.Filename,'img'+str(sample.OnsetFrame)+ftype))。读出来图片是空的，我百度说是图片路径错了，然后我就把绝对路径和相对路径都写了一遍，最后还是返回一个none。又看到说是opencv的版本问题，我又更新了一下opencv，但是还是没用。
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/4d41ee9b-c2d7-4c74-9a86-7e6e98acbedf)

**Comment by whiteany** [comment]
我没有出现过这样的问题，我运行[data_init.py](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/blob/main/preprocess/data_init.py)是这样的。
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/109933797/506bbdc2-8a06-4551-86a0-a399dfb2b99e)
之前只出现过coding.csv里面标记的OnsetFrame,ApexFrame,OffsetFrame与我的数据集不同，修改一下coding.csv里面的数据就行了。

**Comment by whiteany** [comment]
对了，建议你把这个改成绝对路径。D盘什么的加上
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/109933797/0835b653-e06f-4ad0-861b-e3d531f63a40)
改成这样
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/109933797/08f3a891-3e27-43eb-ac8f-1e26acfc75d7)
应该能解决问题。 还有这个程序里面的所有路径都要改成绝对路径。

**Comment by yinlu0221** [comment]
你好，又打扰你了。换成绝对路径还是不对，是不是我数据集图片路径没放对呀？
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/cfca2977-07d2-4e10-8b29-e0b241ee1773)

**Comment by whiteany** [comment]
位置是对的，你把报错的提示发出来啊。

**Comment by yinlu0221** [comment]
我找到出错误的原因了，是代码中那个图片的名字没和数据集图片名字保持一致，所以出来才是空的。

**Comment by yinlu0221** [comment]
你好，打扰了。我在运行LOSO.py是出现了一个错误，你在运行的时候是否出现过？
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/b3cc3096-5adc-4f5e-a0d6-a314cd6de108)

**Comment by whiteany** [comment]
你要查看coding.csv里面的起始帧、顶点帧、结束帧的编号和你的数据是否一致。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue #2)





 
你好，打扰了。我在运行LOSO.py是出现了一个错误，你在运行的时候是否出现过？

**Comment by yinlu0221** [comment]
我把coding.csv里面的各个帧的编号和原始数据集核对了一遍，发现了不一致的地方，然后我改过来了后，重新运行LOSO.py，还是出现上述错误

**Comment by whiteany** [comment]
你把你coding.csv的标题和数据存储的位置发来看一下。

**Comment by whiteany** [comment]
数据存放应该是这样
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/109933797/fc7098b4-225f-4d51-b223-c88f12953d62)

**Comment by yinlu0221** [comment]
嗯是的，数据存放和你一样。
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/40acb534-82a5-41a0-a688-9a7c67dad366)

**Comment by whiteany** [comment]
> 我把coding.csv里面的各个帧的编号和原始数据集核对了一遍，发现了不一致的地方，然后我改过来了后，重新运行LOSO.py，还是出现上述错误
你是如何核对的？人工还是程序核对？

**Comment by yinlu0221** [comment]
我是对着原来数据集里面的xls文件一个一个核对的

**Comment by whiteany** [comment]
> 我是对着原来数据集里面的xls文件一个一个核对的

这是不对的，这个coding和原来数据集里面的xls是一样的，应该。  我的意思是coding文件里面标注的顶峰帧 在实际的文件里面可能没有或者有的文件实际是50-100，而coding里面标注则是36-100，顶峰帧却标注为40。所以会出现list index out of range
。 建议你对程序加个断点，查看具体是哪个标错了。我网络具体是哪个标错了。

**Comment by yinlu0221** [comment]
你说的这个“在实际的文件里面可能没有或者有的文件实际是50-100，而coding里面标注则是36-100，顶峰帧却标注为40”。假如说这个coding.csv里面标号有错误，我觉得前面生成LOF文件就会出错误。因为我发现xls文件里面有一个结束帧标号是错的，和数据集图片不对应。我把这复制到coding.csv文件中，这个sub的光流图片就生成不了。于是我把coding.csv改成和实际数据集图片标号一样，LOF就没有错误了，但是这个为什么还会出现list index out of range

**Comment by whiteany** [comment]
> 你说的这个“在实际的文件里面可能没有或者有的文件实际是50-100，而coding里面标注则是36-100，顶峰帧却标注为40”。假如说这个coding.csv里面标号有错误，我觉得前面生成LOF文件就会出错误。因为我发现xls文件里面有一个结束帧标号是错的，和数据集图片不对应。我把这复制到coding.csv文件中，这个sub的光流图片就生成不了。于是我把coding.csv改成和实际数据集图片标号一样，LOF就没有错误了，但是这个为什么还会出现list index out of range
你说的是对的，但是还是建议你去断点查看到底是为什么出现list index out of range， 光看这个报错给不了实际的解决方案。在我标红的地方加个断点，查看image和data_info的具体内容再作判断。

![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/109933797/31914a05-ab91-4531-ac75-5e77d1067b3c)

**Comment by yinlu0221** [comment]
你好，我想问一下你运行出来的结果是什么，我看只有运行出来ACC，没有显示这个F1-score，UF1 ，UAR 
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/d53ca546-84da-4bad-b6fe-1b54fbc4ff34)

**Comment by yinlu0221** [comment]
你好，我想问一下你运行出来的结果是什么，我看只有运行出来，没有显示这个F1-score，UF1 ，UAR 
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/d53ca546-84da-4bad-b6fe-1b54fbc4ff34)

**Comment by yinlu0221** [comment]
你好，我想问一下你运行出来的结果是什么，我看只有运行出来，没有显示这个F1-score，UF1 ，UAR 
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/d53ca546-84da-4bad-b6fe-1b54fbc4ff34)

**Comment by yinlu0221** [comment]
你好，我想问一下你运行出来的结果是什么，我看只有运行出来ACC，没有显示这个F1-score，UF1 ，UAR 
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/d53ca546-84da-4bad-b6fe-1b54fbc4ff34)

**Comment by whiteany** [comment]
python LOSO.py -e

**Comment by yinlu0221** [comment]
这个checkpoint_casme2_sub01.pth.tar需要自己去下载吗，我看代码里面没有。
![image](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/assets/96124959/378ad926-86a3-427e-a9e5-a15ebaec0f68)

**Comment by yinlu0221** [comment]
你好，我想问一下你跑出来的结果和论文上的结果接近吗

**Comment by whiteany** [comment]
我运行出来不一样。差很多。上面的文件可以下载也可以自己运行程序得到。

**Comment by yinlu0221** [comment]
那你有没有跑过别的文章的代码，结果和论文差别不太大的，能否分享一下源代码？

**Comment by 27Picasso** [comment]
您好，vit的预训练文件能分享一下吗

> 你好，这是我在网上找的一个预训练模型。
> […](#)
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Vision-Intelligence-and-Robots-Group/SLSTT"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2023年11月1日(星期三) 下午4:48
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Vision-Intelligence-and-Robots-Group/SLSTT] 程序应该有个BUG (Issue [#2](https://github.com/Vision-Intelligence-and-Robots-Group/SLSTT/issues/2))
> 
> 
> 
> 
> 
> 
> 你好，请问您跑成功了吗，能否分享一下vit的预训练文件B_16_imagenet1k.pth，我在网上找了很多不太匹配。
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
> 
> 
> 从QQ邮箱发来的超大附件
> 
> B_16_imagenet1k.pth (331.37M, 2023年12月01日 17:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2d6530334135728ee8dff77d13320a4a1d11545500540a0048010950561f5b5553061d07070b00485004095501025e0104075106352138273a54066c5c5f5902000b554704591615110d300e&code=ee03528e

您好，vit的预训练文件能否再分享一下，打扰了

**Comment by whiteany** [comment]
我也忘了从什么地方下载的了，不过你可以研究一下这个工具有可能下载到。https://github.com/lukemelas/PyTorch-Pretrained-ViT

**Comment by 27Picasso** [comment]
> 我也忘了从什么地方下载的了，不过你可以研究一下这个工具有可能下载到。https://github.com/lukemelas/PyTorch-Pretrained-ViT

好的，谢谢您
